server:
  port: 9001
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
  instance:
    instance-id: c1
feign:
  hystrix:
    enabled: true
info:
  app:
    name: consumer
  company:
    name: neusoft
  author:
    name: QYZ