server:
  port: 9002
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: /http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
    register-with-eureka: false
  instance:
    instance-id: c2
feign:
  hystrix:
    enabled: true
