spring:
  application:
    name: register-center
server:
  port: 7002
eureka:
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka2:7002/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
