server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway.com
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
