spring:
  application:
    name: turbine
server:
  port: 9012
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
turbine:
  instanceUrlSuffix:
    default: /hystrix.stream
  app-config-list: provider, consumer
  cluster-name-expression: "'default'"
  combine-host-port: true
