server:
  port: 8001
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 20175377
mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.neu.privoder1.bean

eureka:
  client:
    service-url:
      defaultZone: /http://eureka1:7001/eureka, http://eureka2:7002/eureka, http://eureka3:7003/eureka
  instance:
    instance-id: p1
    prefer-ip-address: true
